/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package renttcar;

/**
 *
 * @author akram
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.itextpdf.text.Document;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.DocumentException;
import javax.swing.JTable;





/**
 *
 * @author laaraf mohamed
 */
public class rentcarsss extends javax.swing.JFrame {

    /**
     * Creates new form rentcarsss
     */
    public rentcarsss() {
        initComponents();
        table_update2();
        populateComboBox();
        
        table_update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    

    Connection con;
    PreparedStatement pst;
        ResultSet Rs=null;
    // <editor-fold defaultstate="collapsed" desc="Generated Code"> 
    
    
    public void generatePDF(JTable table, String filePath) {
        Document document = new Document(PageSize.A4);
        try {
            PdfWriter.getInstance(document, new FileOutputStream(filePath));
            document.open();
            PdfPTable pdfTable = new PdfPTable(table.getColumnCount());
            // Add table headers
            for (int i = 0; i < table.getColumnCount(); i++) {
                pdfTable.addCell(table.getColumnName(i));
            }
            // Add table data
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            for (int i = 0; i < model.getRowCount(); i++) {
                for (int j = 0; j < table.getColumnCount(); j++) {
                    pdfTable.addCell(model.getValueAt(i, j).toString());
                }
            }
            document.add(pdfTable);
        } catch (DocumentException | FileNotFoundException e) {
            e.printStackTrace();
        } finally {
            document.close();
        }
    }
    @SuppressWarnings("unchecked")
    public void table_update2()
     {
         int c;
         try {
             Class.forName("com.mysql.cj.jdbc.Driver");
             con=DriverManager.getConnection("jdbc:mysql://localhost/losrent","laaraf","06102004");
             pst=con.prepareStatement("select * from carregistation");
             ResultSet Rs=pst.executeQuery();
             
             ResultSetMetaData rd=Rs.getMetaData();
             c=rd.getColumnCount();
             DefaultTableModel df=(DefaultTableModel)carsonrenttable.getModel();
             df.setRowCount(0);
             
             
             while(Rs.next())
             {
                 @SuppressWarnings("rawtypes")
                Vector v2=new Vector();
                 for(int i=1;i<=c;i++)
                 {
                     v2.add(Rs.getString("Registrationnum"));
                     v2.add(Rs.getString("Brand"));
                     v2.add(Rs.getString("Model"));
                     v2.add(Rs.getString("Statut"));  
                     v2.add(Rs.getString("Price"));
 
                 }  
                 df.addRow(v2);
             }
             
             } catch (ClassNotFoundException ex) {
             Logger.getLogger(cars.class.getName()).log(Level.SEVERE, null, ex);
         } catch (SQLException ex) {
             Logger.getLogger(cars.class.getName()).log(Level.SEVERE, null, ex);
         }
             
     }
    @SuppressWarnings("unchecked")
    public void table_update()
     {
         int c;
         try {
             Class.forName("com.mysql.cj.jdbc.Driver");
             con=DriverManager.getConnection("jdbc:mysql://localhost/losrent","laaraf","06102004");
             pst=con.prepareStatement("select * from renttable");
             ResultSet Rs=pst.executeQuery();
             
             ResultSetMetaData rd=Rs.getMetaData();
             c=rd.getColumnCount();
             DefaultTableModel df=(DefaultTableModel)carstbleau.getModel();
             df.setRowCount(0);
             
             
             while(Rs.next())
             {
                 @SuppressWarnings("rawtypes")
                Vector v2=new Vector();
                 for(int i=1;i<=c;i++)
                 {
                     v2.add(Rs.getInt("Rentid"));
                     v2.add(Rs.getString("Registration"));
                     v2.add(Rs.getString("Customername"));
                     v2.add(Rs.getString("Rentdate"));  
                     v2.add(Rs.getDate("Returndate"));
                     v2.add(Rs.getInt("Fees"));
 
                 }  
                 df.addRow(v2);
             }
             
             } catch (ClassNotFoundException ex) {
             Logger.getLogger(cars.class.getName()).log(Level.SEVERE, null, ex);
         } catch (SQLException ex) {
             Logger.getLogger(cars.class.getName()).log(Level.SEVERE, null, ex);
         }
             
     }
     private void ResetForm(){
        rentbtn.setText("");
        regbtn.setText("");
        
        cusbtn.setSelectedIndex(0);
        rentbtn1.setText("");
    }
    private void connectToDatabase() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/losrent", "laaraf", "06102004");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(rentcarsss.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(rentcarsss.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

         private void populateComboBox() {
        try {
            connectToDatabase();
            pst = con.prepareStatement("SELECT * FROM customer2");
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                cusbtn.addItem(rs.getString("name"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(rentcarsss.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /* private void updateCarTable1() {
        try {
            // Step 1: Create a JDBC connection to the database
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/losrent", "laaraf", "06102004");
    
            // Step 2: Create a Statement object
            Statement stmt = conn.createStatement();
    
            // Step 3: Execute a SQL SELECT statement to retrieve data from the database table
            ResultSet rs = stmt.executeQuery("SELECT * FROM carregistation");
    
            // Step 4: Create a DefaultTableModel object and set it as the model for the carstbleau JTable
            DefaultTableModel model = new DefaultTableModel();
            carsonrenttable.setModel(model);
    
            // Step 5: Iterate through the ResultSet object and add rows to the DefaultTableModel object
            ResultSetMetaData metaData = rs.getMetaData();
            int columnCount = metaData.getColumnCount();
            while (rs.next()) {
                Object[] row = new Object[columnCount];
                for (int i = 1; i <= columnCount; i++) {
                    row[i - 1] = rs.getObject(i);
                }
                model.addRow(row);
            }
    
            // Step 6: Call the fireTableDataChanged() method of the DefaultTableModel object to update the carstbleau JTable
            model.fireTableDataChanged();
    
            // Close the JDBC resources
           
    
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }  */                  
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        rentbtn = new javax.swing.JTextField();
        returnbtn = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cusbtn = new javax.swing.JComboBox<>();
        savebtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        regbtn = new javax.swing.JTextField();
        editbtn = new javax.swing.JButton();
        rentdatebtn = new com.toedter.calendar.JDateChooser();
        resetbtn = new javax.swing.JButton();
        deletbtn = new javax.swing.JButton();
        rentbtn1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        carstbleau = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        carsonrenttable = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        printbtn = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cars");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Return car");
        jLabel16.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Logout");
        jLabel17.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Customer");
        jLabel18.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 0, 153));
        jLabel15.setText("Cars Rental");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        rentbtn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentbtnActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 0, 153));
        jLabel12.setText("Customer name");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 0, 153));
        jLabel11.setText("Registration");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 0, 153));
        jLabel20.setText("Rent date");
        jLabel20.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        cusbtn.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cusbtn.setForeground(new java.awt.Color(153, 0, 153));
        cusbtn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "mohamed", "soheib" }));
        cusbtn.setToolTipText("");
        cusbtn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cusbtnItemStateChanged(evt);
            }
        });
        cusbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusbtnActionPerformed(evt);
            }
        });

        savebtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        savebtn.setForeground(new java.awt.Color(204, 0, 204));
        savebtn.setText("Save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 153));
        jLabel9.setText("Rent id");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 0, 153));
        jLabel21.setText("Return date");
        jLabel21.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 0, 153));
        jLabel10.setText("Cars List");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        regbtn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        editbtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        editbtn.setForeground(new java.awt.Color(204, 0, 204));
        editbtn.setText("Edit");
        editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbtnActionPerformed(evt);
            }
        });

        rentdatebtn.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        resetbtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        resetbtn.setForeground(new java.awt.Color(204, 0, 204));
        resetbtn.setText("Reset");
        resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtnActionPerformed(evt);
            }
        });

        deletbtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        deletbtn.setForeground(new java.awt.Color(204, 0, 204));
        deletbtn.setText("Delete");
        deletbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletbtnActionPerformed(evt);
            }
        });

        rentbtn1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rentbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentbtn1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 0, 153));
        jLabel13.setText("Fees");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("×");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        carstbleau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Rent id", "Registration", "Customer name", "Rent date", "Return date", "Fees"
            }
        ));
        carstbleau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carstbleauMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(carstbleau);

        carsonrenttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Registration ", "Brand", "Model", "Statut", "Prise"
            }
        ));
        carsonrenttable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carsonrenttableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(carsonrenttable);

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 0, 153));
        jLabel14.setText("Cars on Rent");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        printbtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        printbtn.setForeground(new java.awt.Color(204, 0, 204));
        printbtn.setText("Print");
        printbtn.setToolTipText("");
        printbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1082, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(367, 367, 367)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rentbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(92, 92, 92)
                                        .addComponent(savebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(deletbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(editbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(resetbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(regbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cusbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rentdatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(returnbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rentbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(448, 448, 448))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(printbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(474, 474, 474))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(461, 461, 461))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(jLabel20)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(returnbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cusbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rentbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(regbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(rentdatebtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savebtn)
                    .addComponent(deletbtn)
                    .addComponent(editbtn)
                    .addComponent(resetbtn))
                .addGap(43, 43, 43)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(printbtn)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {                                        
        try {
            java.util.Date DateRent = rentdatebtn.getDate();
            if (DateRent == null) {
                JOptionPane.showMessageDialog(this, "Please select a rental date.");
                return;
            }
            java.sql.Date RentDat = new java.sql.Date(DateRent.getTime());
            java.util.Date DateRet = returnbtn.getDate();
            if (DateRet == null) {
                JOptionPane.showMessageDialog(this, "Please select a return date.");
                return;
            }
            java.sql.Date RetDat = new java.sql.Date(DateRet.getTime());
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/losrent", "laaraf", "06102004");
            pst = con.prepareStatement("insert into renttable(Rentid,Registration,Customername,Rentdate,Returndate,Fees) values (?, ?, ?, ?, ?, ?)");
            pst.setInt(1, Integer.valueOf(rentbtn.getText()));
            pst.setString(2, regbtn.getText());
            pst.setString(3, cusbtn.getSelectedItem().toString());
            pst.setDate(4, RentDat);
            pst.setDate(5, RetDat);
            pst.setInt(6, Integer.valueOf(rentbtn1.getText()));
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Car Updated Successfully..........");
            table_update();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "problem");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "problem2");
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Please fill in all required fields.");
        }
    }                                       

    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {                                        
        @SuppressWarnings("unused")
        DefaultTableModel d1 = (DefaultTableModel) carstbleau.getModel();
    int selectIndex = carstbleau.getSelectedRow();
    
    try {
        if (selectIndex >= 0) {
            
            String make = rentbtn.getText();
            String Bra = regbtn.getText();
            String status = cusbtn.getSelectedItem().toString();
            String pri = rentdatebtn.getDate() != null ? rentdatebtn.getDate().toString() : "";
            String prir = returnbtn.getDate() != null ? returnbtn.getDate().toString() : "";
            String Braa = rentbtn1.getText();
    
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/losrent", "laaraf", "06102004");
    
            pst = con.prepareStatement("update renttable set Registration=?, Customername=?, Rentdate=?, Returndate=?, Fees=? where Rentid=?");

            
            pst.setString(1, make);
pst.setString(2, Bra);
pst.setString(3, status);
pst.setString(4, pri);
pst.setString(5, prir);

// Add the value for Fees here. For example, if you want to set Fees to 500, you can do this:
pst.setDouble(6, 500.0);

pst.setString(6, Braa); // Update the 'Price' column // Update the 'Price' column
             // Match the 'where' clause
    
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Updated");
            table_update();
        } else {
            JOptionPane.showMessageDialog(this, "Please select a row to edit.");
        }
    } catch (ClassNotFoundException | SQLException ex) {
        Logger.getLogger(cars.class.getName()).log(Level.SEVERE, null, ex);
    }          
    }                                       

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {                                         
        ResetForm();
    }                                        

    private void deletbtnActionPerformed(java.awt.event.ActionEvent evt) {                                         
        DefaultTableModel d1 = (DefaultTableModel) carstbleau.getModel();
        int selectIndex = carstbleau.getSelectedRow();
    
        // Check if any row is selected
        if (selectIndex >= 0) {
            String id = d1.getValueAt(selectIndex, 0).toString();
            int dialogResult = JOptionPane.showConfirmDialog(this, "Voulez-vous supprimer l'enregistrement", "Waring", JOptionPane.YES_NO_OPTION);
    
            if (dialogResult == JOptionPane.YES_OPTION) {
                try {
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    con = DriverManager.getConnection("jdbc:mysql://localhost/losrent","laaraf","06102004");
                    pst=con.prepareStatement("delete from renttable where Rentid=?");
                    pst.setString(1, id);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Enregistrement supprimé");
                    table_update();
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(rentcarsss.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
        }
    }                                        

    private void printbtnActionPerformed(java.awt.event.ActionEvent evt) {    
        generatePDF(carstbleau, "C:/Users/User/Desktop/pdf project/Carsonrent.pdf");
        JOptionPane.showMessageDialog(this, "The file pdf is ready to print .");
    }                                        

    private void rentbtnActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       
    @SuppressWarnings("deprecation")
    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {                                      
        Customers customers=new Customers();
        this.hide();
        customers.setVisible(true);
    }                                     
    @SuppressWarnings("deprecation")
    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {                                     
       cars Cars =new cars();
       this.hide();
        Cars.setVisible(true);

    }                                    
    @SuppressWarnings("deprecation")
    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {                                      
        ReturnCars returnCars =new ReturnCars();
        this.hide();
        returnCars.setVisible(true);
    }                                     

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {                                     
        dispose();
    }                                    

    private void rentbtn1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void cusbtnActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void cusbtnItemStateChanged(java.awt.event.ItemEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void carstbleauMouseClicked(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void carsonrenttableMouseClicked(java.awt.event.MouseEvent evt) {                                             
        // TODO add your handling code here:
    }                                            
    @SuppressWarnings("deprecation")
    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {                                      
        login mm =new login();
        this.hide();
            mm.setVisible(true);
    }                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rentcarsss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rentcarsss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rentcarsss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rentcarsss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rentcarsss().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTable carsonrenttable;
    private javax.swing.JTable carstbleau;
    private javax.swing.JComboBox<String> cusbtn;
    private javax.swing.JButton deletbtn;
    private javax.swing.JButton editbtn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton printbtn;
    private javax.swing.JTextField regbtn;
    private javax.swing.JTextField rentbtn;
    private javax.swing.JTextField rentbtn1;
    private com.toedter.calendar.JDateChooser rentdatebtn;
    private javax.swing.JButton resetbtn;
    private com.toedter.calendar.JDateChooser returnbtn;
    private javax.swing.JButton savebtn;
    // End of variables declaration                   
}

